const users = [
  {
    id: 1,
    fotoDePerfil: 'assets/profilePics/1.png',
    nombre: 'Lucas',
    apellido: 'Tissera',
    nickname: 'el.tisser',
    pictures: [1, 2, 3],
  },
  {
    id: 2,
    fotoDePerfil: 'assets/profilePics/2.png',
    nombre: 'shakira',
    apellido: 'Mebarak',
    nickname: 'shaki',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 3,
    fotoDePerfil: 'assets/profilePics/3.png',
    nombre: 'Matias',
    apellido: 'Cabrera',
    nickname: 'mati',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 4,
    fotoDePerfil: 'assets/profilePics/4.png',
    nombre: 'Nicolas',
    apellido: 'Fernandez',
    nickname: 'nico',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 5,
    fotoDePerfil: 'assets/profilePics/5.png',
    nombre: 'Leonardo',
    apellido: 'Dicaprio',
    nickname: 'leo',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 6,
    fotoDePerfil: 'assets/profilePics/6.png',
    nombre: 'Mateo',
    apellido: 'Scheiner',
    nickname: 'matu',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 7,
    fotoDePerfil: 'assets/profilePics/7.png',
    nombre: 'Cristina',
    apellido: 'Perez',
    nickname: 'cris',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 8,
    fotoDePerfil: 'assets/profilePics/8.png',
    nombre: 'Micaela',
    apellido: 'Basano',
    nickname: 'mica',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 9,
    fotoDePerfil: 'assets/profilePics/9.png',
    nombre: 'Florencia',
    apellido: 'Gallardo',
    nickname: 'flor',
    pictures: [4, 5, 6, 7, 8],
  },
  {
    id: 10,
    fotoDePerfil: 'assets/profilePics/10.png',
    nombre: 'Isabella',
    apellido: 'Gomez',
    nickname: 'isa',
    pictures: [4, 5, 6, 7, 8],
  },
];
